// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDun1fdw5jlfvBe7dJuM8W1uHo7bYp6dYk',
    appId: '1:611677459649:android:8cc33d7030e33044dd3040',
    messagingSenderId: '611677459649',
    projectId: 'fir-flutter-demo-4a85c',
    storageBucket: 'fir-flutter-demo-4a85c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQPTJz8Ep-fe-z_W0_HdwuLhHQS9UJclI',
    appId: '1:611677459649:ios:8057d3c87723c808dd3040',
    messagingSenderId: '611677459649',
    projectId: 'fir-flutter-demo-4a85c',
    storageBucket: 'fir-flutter-demo-4a85c.appspot.com',
    androidClientId: '611677459649-ls2fcd9ebk00770abhq6fuqo0eurhmg7.apps.googleusercontent.com',
    iosClientId: '611677459649-6ao3c3t0ah7d9h40j44r5p15t24rl16e.apps.googleusercontent.com',
    iosBundleId: 'com.lecanardnoir.firebaseFlutterDemo',
  );
}
